Products:
  type: object
  properties:
    categories: { type: string }
    weight: { type: number }
    title: { type: string }
    calories: { type: number }
    groupBloodNotAllowed:
      type: array
      items:
        type: boolean
