# docs/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: SlimMom API

  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: SlimMom uygulaması için API dökümantasyonu
tags:
  - name: SlimMOM
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://slimmom-backend-o5ma.onrender.com
paths:
  /auth/register:
    $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    $ref: ../swagger/paths/auth/login.yaml
  /user:
    get:
      $ref: ../swagger/paths/user/get.yaml
    post:
      $ref: ../swagger/paths/user/post.yaml
  /user/profile:
    patch:
      $ref: ../swagger/paths/user/profile/patch.yaml
    get:
      $ref: ../swagger/paths/user/get.yaml
  /user/calorie/private/{date}/allGet:
    $ref: ../swagger/paths/user/calorie/private/%7Bdate%7D/allGet.yaml
  /user/calorie/private/{date}/addPost:
    $ref: ../swagger/paths/user/calorie/private/%7Bdate%7D/addPost.yaml
  /user/calorie/private/{date}/remove/{id}Delete:
    $ref: ../swagger/paths/user/calorie/private/%7Bdate%7D/remove/%7Bid%7DDelete.yaml
  /user/calorie/privatePost:
    $ref: ../swagger/paths/user/calorie/privatePost.yaml
  /user/calorie/public/publicPost:
    $ref: ../swagger/paths/user/calorie/public/publicPost.yaml
  /products:
    $ref: ../swagger/paths/products/searchGet.yaml
    get:
      $ref: ../swagger/paths/products/productsGet.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      $ref: "../swagger/components/schemas/User.yaml"
    Error:
      $ref: "../swagger/components/schemas/Error.yaml"
    SuccessResponse:
      $ref: "../swagger/components/schemas/SuccessResponse.yaml"
  responses:
    NotFound:
      $ref: ../swagger/components/responses/NotFoundError.yaml
    ValidationError:
      $ref: "../swagger/components/responses/ValidationError.yaml"
