# docs/openapi.yaml

openapi: 3.1.0
info:
  version: 1.0.0
  title: SlimMom API

  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: SlimMom uygulaması için API dökümantasyonu
tags:
  - name: SlimMOM
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /auth/register:
    $ref: "../swagger/paths/register.yaml"
  /auth/login:
    $ref: "../swagger/paths/login.yaml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      $ref: "../swagger/components/schemas/User.yaml"
    Error:
      $ref: "../swagger/components/schemas/Error.yaml"
    SuccessResponse:
      $ref: "../swagger/components/schemas/SuccessResponse.yaml"
  responses:
    NotFound:
      $ref: ../swagger/components/responses/NotFoundError.yaml
    ValidationError:
      $ref: "../swagger/components/responses/ValidationError.yaml"
